monitor.alsa.rules = [
  {
    matches = [
      {
        "node.name" = "alsa_output.usb-EDIFIER_EDIFIER_S880DB-00.iec958-stereo"
      }
    ]
    actions = {
      update-props = {
        audio.channels = 2
        audio.position = [ FR FL ]
      }
    }
  }
]
