#!/bin/sh

# for 'deflisten' in eww, but it always ticks
# $6 for memory load
# nvidia-smi dmon -s pu |
#   awk 'NR>2 {print "{\"temp\": " $3 ", \"load\": " $5 "}"; fflush()}'

# holds a string of format '32, 30' (temp, usage)
info=$(nvidia-smi -i 0 --query-gpu=temperature.gpu,utilization.gpu --format=csv,noheader,nounits)
usage=$(echo $info | awk -F', ' '{print $2}')

# for defpoll, much more efficient
if [[ $usage -gt 20 ]]; then
  echo $info | awk -F', ' '{print "{\"temp\": " $1 ", \"load\": " $2 "}"; fflush()}'
else
  echo '{"temp": 0, "load": 0}'
fi
