#!/usr/bin/env bash

getShortName() {
  case "$1" in
    *Colemak*) echo DH ;;
    *English*) echo EN ;;
    *Russian*) echo RU ;;
  esac
}

# get all layouts of all devices to not hardcode keyboard id
layouts=$(hyprctl devices | grep keymap)
getShortName "$layouts"

socat -u UNIX-CONNECT:"$XDG_RUNTIME_DIR"/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while read -r line; do
  [[ "$line" == activelayout* ]] && getShortName "$line"
done
