#!/bin/bash

is_wifi() {
  # 802-11-wireless:wlp1s0 <- on one laptop
  nmcli -t -f TYPE,DEVICE con show --active | grep wireless > /dev/null &&
    return 0 || return 1
}

is_ethernet() {
  nmcli -t -f TYPE,DEVICE con show --active | grep ethernet > /dev/null &&
    return 0 || return 1
}

wifi_signal() {
  nmcli -t -f SIGNAL,ACTIVE device wifi | awk -F':' '{if($2=="yes")print $1}'
}

type() {
  if is_wifi; then
    echo wifi
  elif is_ethernet; then
    echo ethernet
  else
    echo nil
  fi
}

result='{ "type": "'"$(type)"'"'

is_wifi && result="$result"', "wifi_signal": "'"$(wifi_signal)"'"'

result="$result"' }'

echo "$result"
