#!/usr/bin/env bash

vol() {
  wpctl get-volume "@DEFAULT_AUDIO_$1@" | awk '{print int($2*100)}'
}

ismuted() {
  wpctl get-volume "@DEFAULT_AUDIO_$1@" | rg -i muted >/dev/null &&
    echo 'true' || echo 'false'
}

get_info() {
  isvolmuted=$(ismuted "SINK")
  ismicmuted=$(ismuted "SOURCE")
  echo '{ "is_vol_muted": "'"$isvolmuted"'",' \
    '"vol_level": "'"$(vol "SINK")"'",' \
    '"is_mic_muted": "'"$ismicmuted"'",' \
    '"mic_level": "'"$(vol "SOURCE")"'" }'
}

get_info # initial values

# event loop
pactl subscribe | rg --line-buffered "change" | while read -r _; do
  get_info
done
