#!/bin/sh

# https://github.com/chubin/wttr.in#one-line-output
# JSON: "curl 'https://wttr.in/Becici?format=j2'"
# %x for text icon of weather; %f for 'feels like' and %w for wind and arrow-direction
#  not using json cuz too heavy, 2 separate requests seem to be much lighter

location=$(timedatectl | grep "Time zone" | awk '{print $3}' | xargs basename)

# 2 valid args: t (for temperature) and w (for wind)
ip addr show | grep -q "state UP" &&
  curl "https://wttr.in/$location?format=%$1" ||
  echo ''
