#!/usr/bin/env bash

# echo initial value
hyprctl -j activewindow | gojq -r '.title'

socat -u UNIX-CONNECT:"$XDG_RUNTIME_DIR"/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while read -r line; do
  [ "${line%>>*}" == "activewindow" ] && echo "${line#*,}"
done
