#!/usr/bin/env bash
#
# For several monitors support check
# https://github.com/iamverysimp1e/dots/blob/main/configs/eww/scripts/workspaces

# get initial focused workspace
focusedws=$(hyprctl -j monitors | gojq -r '.[] | select(.focused == true) | .activeWorkspace.id')

# generate the json for eww
generate() {
  workspace_count=`hyprctl -j workspaces | gojq -r '. | length'`
  echo -n '['

  for ((i=1; i <= $workspace_count; ++i)); do
    active=`[ $focusedws -eq "$i" ] && echo true || echo false`
    echo -n ''$([ $i -eq 1 ] || echo ,) '{ "number": "'"$i"'", "active": "'"$active"'" }'
  done

  echo ']'
}

# generate initial widget
generate

# main loop
socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while read -r line; do
  if [[ ${line%>>*} =~ (workspace|createworkspace|destroyworkspace) ]]; then
    focusedws=${line#*>>}
    generate
  fi
done
