#!/bin/bash

generate() {
  workspaces="$(hyprctl -j workspaces | gojq -r '. | sort_by(.id)')"
  activeId="$(hyprctl -j activeworkspace | gojq -r '.id')"
  # don't quote on purpose
  echo '{ "items": '$workspaces', "activeId": '$activeId' }'
}

# generate initial widget
generate

# main loop
socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while read -r line; do
  [[ ${line%>>*} =~ (workspace|createworkspace|destroyworkspace|focusedmon) ]] &&
    generate
done
