#!/usr/bin/sh

# fix for when reloading bar when gpu is alredy connected so the bar displays
# correct status
boltctl list | grep -qiE ".*status.*authorized.*" && echo probing_done

boltctl monitor | while read -r line; do
  case "$line" in
    *"BOLT_STATUS_AUTHORIZED"*) echo authorized ;;
    *"Probing done"*) echo probing_done ;;
    *"BOLT_STATUS_DISCONNECTED"*) echo disconnected ;;
  esac
done
