#!/usr/bin/sh

# this script is 10 times faster than prev version:
#
#❯ time (for i in {0..100}; do ./bandwidth > /dev/null 2>&1; done)
# ( for i in {0..100}; do; ./bandwidth > /dev/null 2>&1; done; )  0.85s user 1.04s system 103% cpu 1.842 total
# ❯ time (for i in {0..100}; do ./bandwidthv2 > /dev/null 2>&1; done)
# ( for i in {0..100}; do; ./bandwidthv2 > /dev/null 2>&1; done; )  0.07s user 0.11s system 100% cpu 0.181 total

# ref: https://www.youtube.com/watch?v=w5phSVBEHhQ

logfile="${XDG_CACHE_HOME:+$HOME/.cache}/netlog"
[ ! -e "$logfile" ] && echo '0 0' >"$logfile"
prevdata="$(cat "$logfile")"

rxcurrent="$(/usr/bin/cat /sys/class/net/wlp*/statistics/rx_bytes)"
txcurrent="$(/usr/bin/cat /sys/class/net/wlp*/statistics/tx_bytes)"

echo "$(((rxcurrent - ${prevdata%% *}) / 1024)) $(((txcurrent - ${prevdata##* }) / 1024))"
echo "$rxcurrent $txcurrent" >"$logfile"
