#!/bin/bash

connected() {
  dualsensectl info 2>/dev/null | grep -q build_date
}

charging() {
  status=
  if connected; then
    status=$(dualsensectl battery 2>/dev/null | cut -d ' ' -f 2)
    [ "$status" = "charging" ] && echo "true" || echo "false"
  else
    echo "false"
  fi
}

echo '{ "connected": "'"$(connected && echo "true" || echo "false")"'", ' \
  '"battery": "'"$(connected && dualsensectl battery | cut -d ' ' -f 1 || echo 0)"'", ' \
  '"charging": "'"$(charging)"'" }'
