#+TITLE: /home/sad/dotfiles

I manage the various configuration files in this repo using [[https://www.gnu.org/software/stow/][GNU Stow]]. This
allows me to set up symlinks for all of my dotfiles using a single command: ~stow
.~

* Principles
- *Keyboard Focused*
- [ ] *Minimal Distractions*: check out [[https://polybar.github.io/][Polybar]] and is it even needed with stumpWM
- *Text-based Configuration* of programs i use. This enables me to commit program
  configuration to source control (this repository) so that I can keep
  configurations in sync on all machines I use.
- *Highly Customizable*

* Literate Configuration [[https://leanpub.com/lit-config/read][#source]]
Have a single annotated file for a particular configuration area which
automatically writes out the actual configuration files involved when I save the
.org file.

# - [[file:Emacs.org][Emacs]] - for now in separate .doom.d repo
- Desktop Environment
- Productivity Workflow
- System Configurations via Guix
- Mail with mu4e and isync

** Org Babel Tips
When inside of an Org source block, you can use =org-babel-demarcate-block= (=C-c
C-v d= by default) to split the block you're currently in so that you can insert
an annotation.

=noweb= blocks are extremely useful for configuration organization and sharing
configuration values across files. The [[https://orgmode.org/manual/Noweb-reference-syntax.html][org documentation]] on this topic is
helpful in understanding the different ways you can reference another block in
=noweb= style.

* TODO Guix [[https://guix.gnu.org][#link]]

#+begin_comment
Guix enables to apply this principle to my /entire system configuration/, even
sharing the same base configuration across multiple machines. This has provided
me with a stable, consistent computing experience across the three machines I
use on a regular basis.
#+end_comment

Instructions for installing a system from a Guix configuration can be found in
the [[https://github.com/daviwil/dotfiles/blob/master/Systems.org#system-installation][System Installation]] section.
