#!/usr/bin/sh

files=$(ls "$HOME/Documents/tech/arch_cursors/"*.tar.*z)
# Set $IFS to eliminate whitespace in pathnames.
IFS="$(printf '\n\t')"
DIR=$XDG_DATA_HOME/icons

for file in $files; do
  echo "Extracting $file .."
  tar xf "$file" -C "$DIR"
done
