#!/bin/bash

cursor_path=$HOME/Documents/stuff/arch_cursors
files=$(ls "$cursor_path" | grep -E '.*\.tar..z$')
# Set $IFS to eliminate whitespace in pathnames.
IFS="$(printf '\n\t')"
DIR=$HOME/.icons

for file in $files; do
  echo "Extracting $file .."
  tar xf "$cursor_path/$file" -C "$DIR"
done
