#!/bin/sh

graced=

socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while read -r line; do
  [ "$line" == "openlayer>>lockscreen" ] && graced=$(date +%s)
  if [ "$line" == "closelayer>>lockscreen" ]; then
    timenow=$(date +%s)
    # keep the number value below synced with your grace setting in swaylock conf
    (( timenow - graced > 5 )) && change-theme
  fi
done
