-- NOTE: https://wiki.hyprland.org/Configuring/Environment-variables/
--
-- You can also add a d flag if you want the env var to be exported to D-Bus
-- (systemd only):
-- envd = XCURSOR_SIZE,24

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local display_scale = 1.67 -- or 1.67
hl.env("DISPLAY_SCALE", "$display_scale")
hl.env("TERMINAL", "foot")

hl.env("HYPRCURSOR_THEME", "rose-pine-hyprcursor")
hl.env("HYPRCURSOR_SIZE", "24")

-- toolkit backend variables
-- TODO: manual review — malformed env on line 16: GDK_BACKEND,wayland,x11,*
hl.env("SDL_VIDEODRIVER", "wayland")

-- XDG specifications fail-save
-- better support for screen sharing (Google Meet, Discord, etc)
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")

-- QT Variables
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")

-- for heroic, brave-origin, etc
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")
hl.env("OZONE_PLATFORM", "wayland")

-- needed when no soystemd for telega notifications
-- export $(dbus-launch --exit-with-session)
