-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- /usr/libexec/xdg-desktop-portal-hyprland & # ain't needed with soystemd

-- needs to be started before 'change-theme' script otherwise the latter waits
-- for swaync service to appear
-- update: doesn't need to be started as when installing the aur package it
-- enables service anyway
-- exec-once = swaync

-- fix for logitech bolt receiver waking up system immediately after suspend, see arch wiki
-- force update everything on every hyprland launch
-- preserve the data in the clipboard after the application is closed
-- hot reload any changes in ags bar

-- startup applications

-- Slow app launch fix -- set systemd vars

hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY HYPRLAND_INSTANCE_SIGNATURE XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user start hyprland-session.target")
    hl.exec_cmd("solaar -w hide")
    hl.exec_cmd("change-theme")
    hl.exec_cmd("sync_tz_and_loc -f")
    hl.exec_cmd("wl-paste --watch cliphist store")
    hl.exec_cmd("doom env")
    hl.exec_cmd("foot --server")
    hl.exec_cmd("sleep 10; mbsync mailru")
    hl.exec_cmd("brightnessctl -r")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("find ~/.config/ags -type f -name \"*.js\" | entr -p -s \"systemctl --user restart ags\"")
    hl.exec_cmd("$DOTFILES_PATH/install/first-run/all.sh")
    hl.exec_cmd("gtk-launch brave-origin.desktop", { workspace = "1 silent" })
    hl.exec_cmd("gtk-launch io.element.Element.desktop", { workspace = "2 silent" })
    hl.exec_cmd("systemctl --user import-environment $(env | cut -d'=' -f 1)")
    hl.exec_cmd("dbus-update-activation-environment --systemd --all")
    hl.exec_cmd("systemctl --user start hyprpolkitagent.service")
end)
