-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- NOTE: each require() call is specifically made by Hyprland to be a separate
-- lua “scope”, so errors in one require()d file do not stop execution of other
-- files

-- Source: ~/.config/hypr/env.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("env")
-- Source: ~/.config/hypr/exec-once.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("exec-once")

-- Source: ~/.cache/wal/hyprland-colors.conf — convert this file to Lua and ensure it is on Lua's package.path.
-- require("hyprland-colors")
-- run it immediately (like require's side effects):
-- TODO: check that
dofile(os.getenv("HOME") .. "/.cache/wal/hyprland-colors.lua")

-- or load then call, with error handling:
-- local chunk, err = loadfile(os.getenv("HOME") .. "/dotfiles/hypr-extra/binds.lua")
-- if chunk then chunk() else hl.notification.create({ text = "load fail: " .. err, timeout = 5000, icon = "error" }) end

-- Source: ~/.config/hypr/bindings.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("bindings")
-- Source: ~/.config/hypr/windowrules.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("windowrules")

hl.monitor({
  output = "eDP-1",
  mode = "2880x1920@120.00",
  bitdepth = 10,
  cm = "auto",
  position = "0x0",
  scale = display_scale,
  disabled = true,
})

-- NOTE: 120 fps for phone outputs cuz hyprland might sometimes lower main
-- monitor to match refresh rate of 2nd monitor

-- TODO: dynamically add the monitors and their configs basedon my vnc script

-- Phone vnc output settings when cable connected
hl.monitor({
  output = "vnc_highres",
  -- preferred / maxwidth / highres - all don't take up cutout area
  -- so need to explicitly set orig. pixel 9 screen resolution
  mode = "1212x540@120",
  bitdepth = 10,
  cm = "auto",
  position = "auto-center-right",
  scale = "1.5",
})

-- Phone vnc output settings over network
hl.monitor({
  output = "vnc_lowres",
  -- mode = 606x270@60 # very bad network
  mode = "808x360@60",
  bitdepth = 10,
  cm = "auto",
  position = "auto-center-right",
})

-- samsung old tablet
hl.monitor({
  output = "old_tablet",
  mode = "1024x768@60",
  -- mode = 512x384@60 # 808x360@60 # for networks that can handle at least 16mbps upload
  bitdepth = 10,
  cm = "auto",
  position = "auto-center-down",
})

-- rule for randomly connected monitors
hl.monitor({
  output = "", -- or 1920x1080@60.00Hz
  bitdepth = 10,
  cm = "auto",
  mode = "preferred",
  position = "auto-center-up",
  -- scale = 1.5
  -- mirror = eDP-1
})

-- WORKSPACE RULES
hl.workspace_rule({
  workspace = "1",
  monitor = "eDP-1",
})

hl.workspace_rule({
  workspace = "2",
  monitor = "eDP-1",
  layout = "scrolling",
})

hl.workspace_rule({
  workspace = "4",
  layout = "master",
})

-- EXAMPLE of matching:
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

hl.config({
  general = {
    gaps_in = 2,
    gaps_out = "6",
    border_size = 1,
    col = {
      -- active_border = color5 .. " " .. color6 .. " 45deg",
      inactive_border = "rgba(00000000)",
      -- nogroup_border_active = color5 .. " " .. color6 .. " 45deg", -- inactvie border color
      nogroup_border = "rgba(00000000)", -- $color5 $color6 45deg
    },
    layout = "monocle", -- dwindle / master / scrolling / monocle
    allow_tearing = false, -- DON'T TURN IT ON, breaks games fps
  },
  decoration = {
    rounding = 13,
    rounding_power = 4,
    shadow = {
      enabled = false,
    },
    blur = {
      enabled = true, -- enable dual kavase window background blur
      size = 2, -- minimum 1
      passes = 2, -- minimum 1, more passes = more resource intensive.
      xray = true,
    },
    glow = {
      enabled = true,
      range = 10,
      -- color = color5,
      color_inactive = "rgba(00000000)",
    },
  },

  input = {
    -- --- keyboard ---
    -- https://wiki.hyprland.org/Configuring/Variables/#xkb-settings
    -- man xkeyboard-config
    kb_layout = "us, ru", -- , th
    -- kb_variant = , , pat
    -- kb_layout = us, us, ru
    -- kb_variant = , colemak_dh_iso,
    kb_options = "ctrl:swapcaps, grp:win_space_toggle",
    repeat_rate = 100,
    repeat_delay = 280,
    sensitivity = 1.0, -- mouse input sensitivity. -1.0 to 1.0.
    accel_profile = "flat",
    focus_on_close = 2, -- focus most recent window
    -- follow_mouse = 1 # <- default
    -- float_switch_override_focus = 2 # NOTE: testing again, default - 1, 0 - disabled
    touchpad = {
      -- disable_while_typing = false, -- uncomment when gaming without mouse
      natural_scroll = true,
      tap_to_click = true,
      drag_lock = 0, -- default now
    },
  },
  misc = {
    disable_hyprland_logo = true,
    disable_splash_rendering = true,
    mouse_move_enables_dpms = false,
    focus_on_activate = true,
    key_press_enables_dpms = true,
    animate_manual_resizes = true,
    animate_mouse_windowdragging = true,
    -- blurls = rofi
    on_focus_under_fullscreen = 1,
    vrr = 3, -- fullscreen with `video` or `game` content type
    allow_session_lock_restore = true,
    anr_missed_pings = 3,
  },
  binds = {
    workspace_back_and_forth = true, -- switch to current workspace to switch to previous one
    focus_preferred_method = 1, -- find focus by longer shared edges
    movefocus_cycles_fullscreen = false, -- <- is default on wiki, but seems that not
  },
  xwayland = {
    -- force_zero_scaling = false # default
    use_nearest_neighbor = false,
  },
  render = {
    direct_scanout = 2,
    cm_auto_hdr = 0,
    -- Eclipse apps flickering:
    --  https://github.com/hyprwm/Hyprland/issues/6844#issuecomment-2669164016
  },
  cursor = {
    inactive_timeout = 2,
    hide_on_key_press = true,
    -- NOTE: try setting to 0 if having low gpu usage again
    -- set to 1 for people on stream to see your cursor
    no_hardware_cursors = 2,
    warp_on_change_workspace = 1,
  },
  dwindle = {
    -- 0 - follow mouse, 1 - split to top left, 2 - split to bottom right
    force_split = 0,
  },
  master = {
    new_status = "master",
    mfact = 0.54, -- default .55
    new_on_top = true,
  },
  scrolling = {
    -- direction = down
    follow_min_visible = 0.1, -- 0.4 - default
  },
  debug = {
    disable_logs = false,
    -- enable_stdout_logs = true
  },
  ecosystem = {
    no_update_news = true,
    no_donation_nag = true,
  },
})

-- ANIMATIONS
hl.curve("smoothIn", { type = "bezier", points = { { 0.25, 1 }, { 0.5, 1 } } })
hl.animation({
  leaf = "windows",
  enabled = true,
  speed = 2,
  bezier = "default",
  style = "popin 80%",
})
hl.animation({
  leaf = "windowsOut",
  enabled = true,
  speed = 2,
  bezier = "default",
  style = "popin 90%",
})
hl.animation({
  leaf = "windowsMove",
  enabled = true,
  speed = 4,
  bezier = "default",
})
hl.animation({
  leaf = "layers",
  enabled = true,
  speed = 2,
  bezier = "default",
  style = "fade 60%",
})
hl.animation({
  leaf = "border",
  enabled = true,
  speed = 9,
  bezier = "default",
})
hl.animation({
  leaf = "fade",
  enabled = true,
  speed = 4,
  bezier = "smoothIn",
})
hl.animation({
  leaf = "workspaces",
  enabled = true,
  speed = 2,
  bezier = "default",
  style = "fade",
})
hl.animation({
  leaf = "monitorAdded",
  enabled = true,
  speed = 2,
  bezier = "default",
})

hl.gesture({
  fingers = 3,
  direction = "horizontal",
  action = "workspace",
})
hl.gesture({
  fingers = 3,
  direction = "vertical",
  action = "fullscreen",
})
