
general {
    # dbus/sysd lock command (loginctl lock-session)
    lock_cmd = pidof hyprlock || hyprlock # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session
    on_unlock_cmd = hyprctl dispatch 'hl.exec_cmd("after_sleep_cmds")'
}

listener {
    timeout = 300
    # don't actually need timeout locking
    # on-timeout = loginctl lock-session
    on-resume = hyprctl dispatch 'hl.exec_cmd("change-theme")'
}
