-- --- Apps ---

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.bind(mainMod .. " + A", hl.dsp.submap("apps"))
hl.define_submap("apps", function()
  hl.bind(mainMod .. " + S", hl.dsp.exec_cmd("gtk-launch steam.desktop"))
  hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd("pkill -9 steam"))
  hl.bind(mainMod .. " + E", hl.dsp.exec_cmd("emacsclient -c || emacs"))
  hl.bind(mainMod .. " + V", hl.dsp.exec_cmd("easyeffects"))
  hl.bind(mainMod .. " + D", hl.dsp.exec_cmd("pkill -f -9 element || gtk-launch element.desktop"))
  hl.bind(mainMod .. " + N", hl.dsp.exec_cmd("xdg-terminal-exec --app-id=TUI.float nvtop"))
  hl.bind(mainMod .. " + T", hl.dsp.exec_cmd("xdg-terminal-exec --app-id=TUI.float nethogs"))
  hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("xdg-terminal-exec --app-id=TUI.float wiremix"))
  hl.bind(mainMod .. " + P", hl.dsp.exec_cmd("xdg-terminal-exec --app-id=TUI.float btop"))
  hl.bind(mainMod .. " + B", hl.dsp.exec_cmd("xdg-terminal-exec --app-id=TUI.float bluetui"))
  hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("xdg-terminal-exec --app-id=TUI.float systemctl-tui -s user"))
  hl.bind(
    mainMod .. " + SHIFT + L",
    hl.dsp.exec_cmd("xdg-terminal-exec --app-id=TUI.float -e sudo systemctl-tui -s global")
  )
  -- NOTE: alternative:
  -- curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python -
  hl.bind(mainMod .. " + I", hl.dsp.exec_cmd("xdg-terminal-exec --app-id=TUI.float speedtest"))
  hl.bind(mainMod .. " + H", hl.dsp.exec_cmd("gtk-launch heroic.desktop"))
  hl.bind(mainMod .. " + bracketleft", hl.dsp.submap("reset"))
  hl.bind("catchall", hl.dsp.submap("reset"))
end)

-- --- Rofi ---

hl.bind(mainMod .. " + E", hl.dsp.submap("rofi"))
hl.define_submap("rofi", function()
  hl.bind(mainMod .. " + O", hl.dsp.exec_cmd("pkill rofi || rofi -show-icons -show combi"))
  -- passing cache-dir from here cuz idk how to pass XDG_CACHE_HOME to rofi config
  -- bind = SUPER, I, exec, pkill rofi || rofi -show run -cache-dir $XDG_CACHE_HOME/rofi
  hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("kill rofi || rofi-wp"))
  hl.bind(mainMod .. " + B", hl.dsp.exec_cmd("kill rofi || rofi-bt"))

  hl.bind(mainMod .. " + I", hl.dsp.exec_cmd("kill rofi || rofi-pacman"))
  hl.bind(mainMod .. " + SHIFT + I", hl.dsp.exec_cmd("kill rofi || rofi-aur"))
  hl.bind(mainMod .. " + R", hl.dsp.exec_cmd("kill rofi || rofi-pacman -r"))
  -- bind = SUPER, I, exec, xdg-terminal-exec --app-id=TUI.float omarchy-pkg-install
  -- bind = SUPERSHIFT, I, exec, xdg-terminal-exec --app-id=TUI.float omarchy-pkg-aur-install
  -- bind = SUPER, R, exec, xdg-terminal-exec --app-id=TUI.float omarchy-pkg-remove

  hl.bind(mainMod .. " + K", hl.dsp.exec_cmd("kill rofi || rofi-kaomoji"))
  hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("kill rofi || rofi-bookmarks"))
  hl.bind(mainMod .. " + P", hl.dsp.exec_cmd("kill rofi || rofi-pass"))
  hl.bind(mainMod .. " + N", hl.dsp.exec_cmd("kill rofi || rofi-network"))
  hl.bind(
    mainMod .. " + Y",
    hl.dsp.exec_cmd("kill rofi || cliphist list | rofi -i -dmenu -display-columns 2 | cliphist decode | wl-copy")
  )

  -- rarely used
  hl.bind(mainMod .. " + U", hl.dsp.exec_cmd("pkill rofi || rofi-udiskie"))
  hl.bind(mainMod .. " + 0", hl.dsp.exec_cmd("pkill rofi || rofi-0x0"))
  hl.bind(mainMod .. " + F", hl.dsp.exec_cmd("pkill rofi || rofi-flatpak"))
  hl.bind(mainMod .. " + SHIFT + F", hl.dsp.exec_cmd("pkill rofi || rofi-flatpak -r"))
  hl.bind(mainMod .. " + G", hl.dsp.exec_cmd("pkill rofi || rofi-powerprofile"))

  hl.bind(mainMod .. " + bracketleft", hl.dsp.submap("reset"))
  hl.bind("catchall", hl.dsp.submap("reset"))
end)

-- --- Translate ---

hl.bind(mainMod .. " + U", hl.dsp.submap("translate"))
hl.define_submap("translate", function()
  hl.bind(mainMod .. " + U", hl.dsp.exec_cmd("kill rofi || rofi-translate"))
  hl.bind(mainMod .. " + SHIFT + U", hl.dsp.exec_cmd("kill rofi || rofi-translate t"))
  hl.bind(mainMod .. " + E", hl.dsp.exec_cmd('say -e -u critical "$(trans -sl en -tl ru "$(wl-paste)")"'))
  hl.bind(mainMod .. " + R", hl.dsp.exec_cmd('say -e -u critical "$(trans -sl ru -tl en "$(wl-paste)")"'))
  hl.bind(mainMod .. " + bracketleft", hl.dsp.submap("reset"))
  hl.bind("catchall", hl.dsp.submap("reset"))
end)

-- --- Work stuff ---

hl.bind(mainMod .. " + V", hl.dsp.submap("work"))
hl.define_submap("work", function()
  hl.bind(
    mainMod .. " + D",
    hl.dsp.exec_cmd("xdg-open \"$(grep daily ~/Documents/quickmarks | cut -d' ' -f2)\" >/dev/null 2>&1")
  )
  hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("togglevpn cisco"))
  hl.bind("catchall", hl.dsp.submap("reset"))
end)

-- --- Theme / wallpapers ---

hl.bind(mainMod .. " + W", hl.dsp.submap("theme"))
hl.define_submap("theme", function()
  hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("change-theme"))
  hl.bind(mainMod .. " + D", hl.dsp.exec_cmd("change-theme -d"))
  hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("change-theme -l"))
  hl.bind(mainMod .. " + SHIFT + D", hl.dsp.exec_cmd("change-theme -D"))
  hl.bind(mainMod .. " + bracketleft", hl.dsp.submap("reset"))
  hl.bind("catchall", hl.dsp.submap("reset"))
end)

-- --- Screenshots ---

-- bindO - hold to trigger
hl.bind(mainMod .. " + S", hl.dsp.exec_cmd("screenshot --fulltoboth"), { long_press = true })
hl.bind(mainMod .. " + S", hl.dsp.submap("screenshot"))
hl.define_submap("screenshot", function()
  hl.bind(mainMod .. " + F", hl.dsp.exec_cmd("screenshot --fulltoboth"))
  hl.bind(mainMod .. " + SHIFT + F", hl.dsp.exec_cmd("screenshot --fulltoclip"))
  -- 's' for select
  hl.bind(mainMod .. " + S", hl.dsp.exec_cmd("screenshot --parttoclip"))
  hl.bind(mainMod .. " + N", hl.dsp.exec_cmd("screenshot --parttoclipnofreeze"))
  hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd("screenshot --parttoboth"))
  -- 'd' for draw
  hl.bind(mainMod .. " + D", hl.dsp.exec_cmd("screenshot --drawtoclip"))
  hl.bind(mainMod .. " + SHIFT + D", hl.dsp.exec_cmd("screenshot --drawtoboth"))
  -- 'o' for OCR
  hl.bind(mainMod .. " + O", hl.dsp.exec_cmd("screenshot --ocr"))
  hl.bind(mainMod .. " + SHIFT + O", hl.dsp.exec_cmd("screenshot --otpdecode"))
  hl.bind(mainMod .. " + R", hl.dsp.exec_cmd("screenshot --ocr-ru"))
  hl.bind(mainMod .. " + bracketleft", hl.dsp.submap("reset"))
  hl.bind("catchall", hl.dsp.submap("reset"))
end)

-- --- Notifications ---

hl.bind(mainMod .. " + N", hl.dsp.submap("notifs"))
hl.define_submap("notifs", function()
  hl.bind(mainMod .. " + N", hl.dsp.exec_cmd("swaync-client -t"))
  hl.bind(mainMod .. " + H", hl.dsp.exec_cmd("swaync-client --hide-latest"))
  -- closes latest only if those are still 'floating', not in control-center
  -- bind = SUPER, C, exec, swaync-client --close-latest
  hl.bind(mainMod .. " + C", hl.dsp.exec_cmd("swaync-client -C"))
  hl.bind(mainMod .. " + R", hl.dsp.exec_cmd("sh ~/.config/swaync/reload.sh"))
  -- default reset to go back to the global submap

  hl.bind(mainMod .. " + bracketleft", hl.dsp.submap("reset"))
  hl.bind("catchall", hl.dsp.submap("reset"))
end)
