#+title: Pacman
#+SOURCE: hooks source - https://forum.manjaro.org/t/creating-useful-pacman-hooks/55020

- Before updating ~HooksDir~ move there all hooks from hooks from previous hooks
  dir. (cuz it removed all my artix hooks when i changed it)
- use [[https://archlinux.org/mirrorlist/?country=RU&protocol=https&ip_version=4&ip_version=7][pacman mirrorlist generator]] to get links relevant for your location. (Hook
  files syntax documentation links: [[https://man.archlinux.org/man/core/pacman/alpm-hooks.5.en][man 5 alpm-hooks]], [[https://wiki.archlinux.org/title/Pacman#Hooks][pacman@hooks #archlinux]])

** reflector
- pmi reflector
- ssce --now reflector
** System boostrap
- [[https://www.makeuseof.com/install-and-use-yay-arch-linux/#how-to-install-yay-on-arch-linux][install yay]]
- add =Include = /home/earthian/.config/pacman/pacman.conf= to [options] section
  in etc/pacman.conf. *Comment* 'Hooks' line in =pacman.conf= because otherwise it
  will overwrite our pkglist files. Uncomment =[multilib]= section in
  =/etc/pacman.conf=
- yi - < ~/.config/pacman/foreignpkglist.txt (important to install pacmages
  from yay first to avoid further conflicts)
- [[*reflector][Set up reflector]]
- pmi - < ~/.config/pacman/pkglist.txt
- now uncomment that hooks line.
