
# source: https://github.com/egeesin/pywal2alacritty/blob/master/script.sh

# Write new color definitions
# We know $colorX is unset, we set it by sourcing above
[colors.primary]
background = '{color0}'
foreground = '{color7}'

[colors.cursor]
text   = '{color0}' # Apply background color to color of text inside cursor
cursor = '{color7}' # Apply foreground color to color of cursor

[colors.vi_mode_cursor]
text    = '{color0}' # Same as above
cursor  = '{color7}'

[colors.search.matches]
foreground = '{color0}' # Same as above
background = '{color15}' # Apply bright/white color to bg color of matching search

[colors.search.focused_match]
foreground = 'CellBackground'
background = 'CellForeground'

[colors.line_indicator]
foreground = 'None'
background = 'None'

[colors.footer_bar]
foreground = '{color8}'
background = '{color7}'

[colors.selection]
text       = 'CellBackground'
background = 'CellForeground'

[colors.normal]
black   = '{color0}'
red     = '{color1}'
green   = '{color2}'
yellow  = '{color3}'
blue    = '{color4}'
magenta = '{color5}'
cyan    = '{color6}'
white   = '{color7}'

[colors.bright]
black   = '{color8}'
red     = '{color9}'
green   = '{color10}'
yellow  = '{color11}'
blue    = '{color12}'
magenta = '{color13}'
cyan    = '{color14}'
white   = '{color15}'
