Net/ThemeName "Orchis-Dark-Compact"
Net/IconThemeName "Numix-Circle"
Gtk/CursorThemeName "BreezeX-RosePine-Linux"
Net/EnableEventSounds 0
EnableInputFeedbackSounds 0
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintslight"
Xft/RGBA "rgb"
