#!/bin/bash

action=install

while getopts ":ri" Option; do case $Option in
  i) action=install ;;
  r) action=remove ;;
  *) action=install ;;
esac done

case $action in
  "install")
    pkg=$(pacman -Si |
            awk -F ' : ' '
/^Name/{name=$2}
/^Description/{description=$2}
/^Download Size/{size=$2}
/^Installed Size/{size_i=$2;
print name, "「 "size" →", size_i" 」", description} ' |
            sort -d | rofi -dmenu -i | awk '{print $1}')

    # Name [Download Size] (Repo) => Description

    [ -z "$pkg" ] && exit 0

    sudo pacman -S --noconfirm "$pkg" &&
      say "Installed 📦 $pkg" || say "Failed to install 📦 $pkg"
    ;;
  "remove")
    pkg=$(yay -Qi |
      awk -F ' : ' '
/^Name/{name=$2}
/^Description/{description=$2}
/^Installed Size/{size=$2;
print name, "「 "size" 」", description} ' |
      sort -d | rofi -dmenu -i | awk '{print $1}')

    [ -z "$pkg" ] && exit 0

    sudo pacman -R --noconfirm "$pkg" &&
      say "Removed 📦 $pkg" || say "Failed to remove 📦 $pkg"
    ;;
esac
