#!/bin/bash

action=install

while getopts ":ri" Option; do case $Option in
  i) action=install ;;
  r) action=remove ;;
esac done

case $action in
  "install")
    pkg=$(pacman -Si |
      awk '/^Name/{name=$3} /^Download Size/{size=$4$5} /^Repo/{repo=$3} /^Description/{sub(/^.{18}/,"",$0); print name, "["size"]", "("repo") =>", $0} ' |
      sort -d | rofi -dmenu -i | awk '{print $1}')

    sudo pacman -S --noconfirm "$pkg" && say "Installed 📦 $pkg"
    ;;
  "remove")
    pkg=$(pacman -Qi |
      awk '/^Name/{name=$3} /^Installed Size/{size=$4$5} /^Description/{sub(/^.{18}/,"",$0); print name, "["size"] =>", $0} ' |
      sort -d | rofi -dmenu -i | awk '{print $1}')

    sudo pacman -R --noconfirm "$pkg" && say "Removed 📦 $pkg"
    ;;
esac
