#!/bin/sh

wp_dir="$HOME/Pictures/DCIM/wps/pc"

list_wps() {
  find "$wp_dir" -type f -printf "%P\n" |
    while read -r wp; do
      printf '%s\x00icon\x1f%s/%s\n' "$wp" "$wp_dir" "$wp"
    done
}

rofi_dmenu() {
  # handwriting fonts: caveat #1 swankyandmoomoo #2 longcang #3
  rofi -dmenu -i -show-icons \
    -theme-str '#element-text { font: "caveat 17"; }' \
    -theme-str '#entry { placeholder: "Wallpaper to apply.."; }'
}

wp=$(list_wps | rofi_dmenu)

[ ! -z $wp ] && change-theme -w "$wp_dir/$wp"
