#!/usr/bin/env bash

wp_dir="$HOME/Pictures/DCIM/wps/pc"

list_wps() {
  find "$wp_dir" -type f -printf "%P\n" |
    while read -r wp; do
      printf '%s\x00icon\x1f%s/%s\n' "$wp" "$wp_dir" "$wp"
    done
}

rofi_dmenu() {
  # handwriting fonts: caveat #1 swankyandmoomoo #2 longcang #3
  rofi -dmenu -i -show-icons -theme-str "
  #element-text { font: \"caveat 17\"; }
  #entry { placeholder: \"Wallpaper to apply..\"; }
  element-icon {
    border-radius: 10;
    size: 100;
    padding: -25px 0px;
    margin: 0 10 0 0;
  }
"
}

wp=$(list_wps | rofi_dmenu)

[[ "$?" -ne 1 && -n "$wp" ]] && change-theme -w "$wp_dir/$wp"
