#!/usr/bin/sh

# 'Return' opens selected entry via xdg-open
# 'Ctrl + Space' (rofi bindings) completes selected entry

# man rofi-keys

# adds bookmark to your bookmarks file
add_bookmark="Control+Return"
# copy bookmark line to clipboard (in case you want to create it edited and just
#   to be save) and removes chosen bookmark from file
remove_bookmark="Alt+k"
# does same as 'Alt + k', but keeps menu opened
remove_bookmarks="Alt+K"
# copies selected bookmark to clipboad (wayland only)
yank_bookmark="Alt+y"
open_in_emacs="Control+e"

bookmarks_file="$HOME/Documents/quickmarks"

show_menu() {
  bookmark=$(rofi -dmenu -i \
    -theme-str '#entry { placeholder: "Open/yank/kill bookmark:"; }' \
    -kb-custom-1 "$add_bookmark" \
    -kb-accept-custom "" \
    -kb-move-end "" \
    -kb-custom-2 "$remove_bookmark" \
    -kb-custom-3 "$remove_bookmarks" \
    -kb-custom-4 "$yank_bookmark" \
    -kb-custom-5 "$open_in_emacs" \
    -input "$bookmarks_file")

  rofi_exit=$?

  [ $rofi_exit -eq 1 ] && exit

  url=$(echo "$bookmark" | cut -d ' ' -f 2)

  case $rofi_exit in
    10)
      echo "$bookmark" >>"$bookmarks_file"
      sort -u -o "$bookmarks_file" "$bookmarks_file"
      ;;
    11 | 12)
      # copy only on normla delete, because i suppose that when user will use
      # delete with reappearing menu (Alt + K) he most likely already has
      # something in clipboard to replace deleted entry with
      [ $rofi_exit -eq 11 ] && wl-copy "$bookmark"
      # Escape special characters
      escaped_bookmark=$(echo "$bookmark" | sed 's/[][\/.*^$]/\\&/g')
      sed -i "/$escaped_bookmark/d" "$bookmarks_file"
      [ $rofi_exit -eq 12 ] && show_menu
      ;;
    13) wl-copy "$url" ;;
    14)
      pgrep emacs &&
        emacsclient -e "(progn (require (quote eww)) (eww \"$url\"))" &&
        hyprctl dispatch focuswindow class:Emacs
      ;;
    *) xdg-open "$url" ;;
  esac
}

show_menu

exit 0
