#!/usr/bin/sh

extended="$1" # run extended version of the script

text=$(rofi -dmenu)

rofi_exit=$?
[ $rofi_exit -eq 1 ] && exit

pick_lang() {
  default="$1"
  placeholder="$2"
  [ -z "$default" ] && default=English
  lang_line="$(trans -list-all |
    rofi -i -dmenu -display-columns 2 -display-column-separator "\s+" \
      ${placeholder:+-theme-str "#entry { placeholder: \"$placeholder\"; }"} \
      -select "$default")"

  rofi_exit=$?
  [ $rofi_exit -eq 1 ] && kill -INT $$ # kill from subshell by pid

  echo "$lang_line" | awk '{print $1}'
}

[ -n "$extended" ] && source_lang="$(pick_lang English 'Source language..')"

target_lang="$(pick_lang "Russian" 'Target lanaguage..')"

result=$(trans -show-original n -show-original-phonetics n \
  -show-translation-phonetics n -no-ansi -indent 2 \
  ${source_lang:+-sl "$source_lang"} -tl "$target_lang" "'$text'")

say -e -u critical "$result"

exit
