#!/usr/bin/env bash

# NOTE: KAOMOJIS file taken from https://git.sr.ht/~pkal/insert-kaomoji
# convenient for me since i also use this emacs package

moji_dir=$(dirname "$0")
moji_path="$moji_dir/KAOMOJIS"
categories=$(grep -o -E '\<[A-Z][a-z]{2,}\>' "$moji_path")

show_menu() {
  # force monospace font to not get those fields messy
  category=$(echo -e "$categories" |
               rofi -dmenu -i -theme-str '#entry { placeholder: "Choose kaomoji:"; }' \
                 -theme-str '* { font: "syne mono 13"; }')

  [ -z "$category" ] && exit 0

  line=$(grep "$category" "$moji_path")
  # trim one specitl sign from the end
  line="${line%*}"
  # trim another special sign from the beginning, including category names
  line="${line#*}"
  line="$lineback"

  selection=$(echo "$line" | awk -F'' '{for(i=1; i<=NF; i++) print $i}' |
                rofi -dmenu -i -theme-str '* { font: "syne mono 13"; }')

  [ "$selection" = "back" ] && show_menu || wl-copy "$selection"
}

show_menu

exit 0
