#+title: Arch

** Installation
- follow official arch installation guide
- _disk partitioning_ (using /fdisk/):
  - check your disks sda's / nvme's: ~lsblk~ or ~fdisk -l~. (Results ending in rom,
    loop or airoot may be ignored.)
  - ~p~ - list all partitions that u currently have
  - ~g~ - create new gpt-partition table (or ~d~ to delete particular ones)
  - ~n[ew]~ -> 1 (default) -> 2048 (default) -> +1G (efi partition) (tho wiki
    recommends +512M)
  - ~n~ -> 3x enter (root partition)
  - ~t[ype]~ -> 1st partition (efi one) -> l[ist] to get all available types ->
    choose EFI system
  - set root partition type to /Linux filesystem/
  - ~p~ -> check which partitions you ended up with
  - ~w[rite]~ if everything is as u want
- _pacstrap_: ~pacstrap -K /mnt base base-devel linux linux-firmware linux-headers
  sof-firmware networkmanager wget vim man-db man-pages texinfo intel/amd-ucode~
- ...
- bootloader step:
  - pacman -S grub efibootmgr
  - grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=grub
  - grub-mkconfig -o /boot/grub/grub.cfg
- *after reboot*:
  - systemctl enable --now NetworkManager -> nmtui
  - create user:
    - useradd -m -G wheel earthian
    - passwd earthian
    - ~EDITOR=vim visudo~ -> uncomment wheel
  - *FROM NOW ON DO THINGS ONLY AS NORMAL USER, NOT ROOT*
  - wget https://raw.githubusercontent.com/Seme4eg/dotfiles/master/Makefile
  - ~make ssh~ -> add ssh pub key that's stored in printed 0x0 link to github
  - ~make install~
  - for *nvidia* machines install /nvidia, nvidia-prime, libva-nvidia-driver-git/,
    for *amd* /mesa/
  - ~make postinstall~
  - reboot, wait 5 secs for internet, login, launch hyprland, ~make postreboot~
  - setup [[*gpg][gpg]]
  - also check some of the targets in makefile that need to be run manually

NOTE: (!) [[https://wiki.archlinux.org/title/Users_and_groups#Pre-systemd_groups][pre-systemd groups]] <- no need to usermod video, audio, power etc, if
something won't work go to 'udev' page from this link

** sound
get info on your cards: ~pactl list cards~

If there's _no sound_, maybe you've several sound cards and default one got set
incorrectly, then create ~/.asoundrc to change default sound card:
#+begin_src
defaults.ctl.card 1
defaults.pcm.card 1
#+end_src

: man pactl

If your soundcard doens't correctly detect microphone plugged in a 4-pin 3.5mm
(TRRS) jack, find your soundcard name (easy to do using alsamixer) and go
[[https://wiki.archlinux.org/title/Advanced_Linux_Sound_Architecture#Correctly_detect_microphone_plugged_in_a_4-pin_3.5mm_(TRRS)_jack][research]]. (Maybe you just need to switch to in in pavucontrol..). Just examples
of what previously worked for me on different machines (file
=/etc/modprobe.d/alsa-base.conf=):
- options snd-sof-intel-hda-common hda_model=alc298-dell-aio
- options snd-hda-intel model=alc298-dell-aio
- options snd-hda-intel model=dell-headset-multi

- switch default mic to the one on your headphones cuz notebook mic is
  usually crap: ~wpctl status~ - grab id of your mic (SOURCE device) - ~wpctl
  set-default ...~

When encountering problems with sound: ~/usr/bin/rm -r
~/.local/state/wireplumber/~, ~scur wireplumber.service~

** hyprland
- _Nvidia hybrid laptop setup_: install /nvidia/ drivers, done. In order for HDMI
  port to work (which is often connected directly to Nvidia gpu) hyprland must
  be able to be launched only using Nvidia gpu (do it via ~WLR_DRM_DEVICES~ var).
  If it launches you're good to go. Otherwise set ~nvidia-drm.modeset=1~ in
  =/etc/default/grub=, check again and if it works - HDMI will b working (tho i
  recommend to use USB-C hub and plug HDMI in there so external monitor apps use
  Intel GPU cuz for now nvidia is glichy).
- _Nvidia pc setup_: install /nvidia-dkms/, then enable drm in grub conf:
  - ~GRUB_CMDLINE_LINUX_DEFAULT="loglevel=3 quiet nvidia_drm.modeset=1"~
  - done

** gpg
- copy secret.gpg from wherever you have it stored and run ~gpg --import
  secret.gpg~
- set *trust* level with ~gpg --edit-key <KEY_ID>~ -> gpg> trust -> 5 -> y

** fingerprint sensor
https://wiki.archlinux.org/title/fprint

my xiaomi notebook pro x 2021 fingerprint sensor won't prob ever b supported
tho: https://gitlab.freedesktop.org/libfprint/wiki/-/wikis/Unsupported-Devices

xiaomi 2016 has a supported fprint sensor but enrolled prints never match.. so
the whole fprint thing to me appeared as unreliable.

