#+title: Arch

** Installation
- follow official arch installation guide
- _disk partitioning_ (using /fdisk/):
  - check your disks sda's / nvme's: ~lsblk~ or ~fdisk -l~. (Results ending in rom,
    loop or airoot may be ignored.)
  - ~p~ - list all partitions that u currently have
  - ~g~ - create new gpt-partition table (or ~d~ to delete particular ones)
  - ~n[ew]~ -> 1 (default) -> 2048 (default) -> +1G (efi partition) (tho wiki
    recommends +512M)
  - ~n~ -> 3x enter (root partition)
  - ~t[ype]~ -> 1st partition (efi one) -> l[ist] to get all available types ->
    choose EFI system
  - set root partition type to /Linux filesystem/
  - ~p~ -> check which partitions you ended up with
  - ~w[rite]~ if everything is as u want
- _pacstrap_: ~pacstrap -K /mnt base base-devel linux linux-firmware linux-headers
  sof-firmware networkmanager wget neovim man-db man-pages intel/amd-ucode~
- ...
- bootloader step:
  - pacman -S grub efibootmgr
  - grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=grub
  - grub-mkconfig -o /boot/grub/grub.cfg
- *after reboot*:
  - systemctl enable --now NetworkManager -> nmtui
  - create user:
    - useradd -m -G wheel earthian
    - passwd earthian
    - ~EDITOR=vim visudo~ -> uncomment wheel
  - *FROM NOW ON DO THINGS ONLY AS NORMAL USER, NOT ROOT*
  - further steps in main readme file

** sound
- switch default mic to the headset one: ~wpctl status~ - grab id of your mic
  (SOURCE device) - ~wpctl set-default ...~
- also have some cards disabled in =51-alsa-disable.conf=. Each time you change
  this file - ~scur wireplumber~

Some info for _debugging_ some sound/mic problems:
- ~man pactl~
- get info on your cards: ~pactl list cards [short]~
- To output card names ~cat /proc/asound/modules/~.
- To output soundcard into ~cd /sys/module/snd_hda_intel/parameters/~ and cat files there.
- When encountering problems with sound: ~/usr/bin/rm -r ~/.local/state/wireplumber/~, ~scur wireplumber.service~
- If there's _no sound_, maybe you've several sound cards and default one got set
  incorrectly, then create =~/.asoundrc= to change default sound card:

#+begin_src
defaults.ctl.card 1
defaults.pcm.card 1
#+end_src

_Fixing microphone plugged in a 4-pin 3.5mm (TRRS) jack_:
- find your soundcard name using /alsamixer/ or whatever and go [[https://wiki.archlinux.org/title/Advanced_Linux_Sound_Architecture#Correctly_detect_microphone_plugged_in_a_4-pin_3.5mm_(TRRS)_jack][research]]
- For xiaomi laptop: =/etc/modprobe.d/alsa-base.conf=:
  - options snd-sof-intel-hda-common hda_model=alc298-dell-aio

_asus zenbook headset mic fix:_
- sir from this thread saved my life:
  https://bbs.archlinux.org/viewtopic.php?id=281641 (tldr: hdajackretask >
  Choose the correct card > "Show Unconnected Pins" > 0x19 > "Override" >
  "Microphone")

** hyprland
- _Nvidia hybrid laptop setup_: install /nvidia/ drivers, done. In order for HDMI
  port to work (which is often connected directly to Nvidia gpu) hyprland must
  be able to be launched only using Nvidia gpu (do it via ~WLR_DRM_DEVICES~ var).
  If it launches you're good to go. Otherwise set ~nvidia-drm.modeset=1~ in
  =/etc/default/grub=, check again and if it works - HDMI will b working (tho i
  recommend to use USB-C hub and plug HDMI in there so external monitor apps use
  Intel GPU cuz for now nvidia is glichy).

** gpg
- import all needed gpg keys - ~gpg --import <keyname>.gpg~, including the one for ~git-crypt~
- set *trust* level with ~gpg --edit-key <KEY_ID>~ -> gpg> trust -> 5 -> y

** Other fixes
Xiomi laptop was draining battery like crazy in [s2idle] sleep mode, so i
changed added the ~mem_sleep_default=deep~ to ~GRUB_CMDLINE_LINUX_DEFAULT~ in =/etc/default/grub=
