
fps = 60.0 # Limit rendering frames per second (unlimited if unset)
theme = "default" # Theme to use (see Themes section)
tab = "input" # Initial tab
enforce_max_volume = false # Whether to prevent increasing volume past max_volume

keybindings = [
 # Changed defaults:
 { key = { Char = "L" }, action = { SetRelativeVolume = 0.01 } },
 { key = { Char = "H" }, action = { SetRelativeVolume = -0.01 } },
 { key = { Char = "l" }, action = "TabRight" },
 { key = "Tab", action = "TabRight" },
 { key = { Char = "h" }, action = "TabLeft" },
 { key = "BackTab", modifiers = "SHIFT", action = "TabLeft" },

 # Unsetting default bindings to show less stuff in help menu:
 { key = "Down", action = "Nothing" },
 { key = "Up", action = "Nothing" },
 { key = "Right", action = "Nothing" },
 { key = "Left", action = "Nothing" },
 { key = { Char = "`" }, action = "Nothing" },
 { key = { Char = "1" }, action = "Nothing" },
 { key = { Char = "2" }, action = "Nothing" },
 { key = { Char = "3" }, action = "Nothing" },
 { key = { Char = "4" }, action = "Nothing" },
 { key = { Char = "5" }, action = "Nothing" },
 { key = { Char = "6" }, action = "Nothing" },
 { key = { Char = "7" }, action = "Nothing" },
 { key = { Char = "8" }, action = "Nothing" },
 { key = { Char = "9" }, action = "Nothing" },
 { key = { Char = "0" }, action = "Nothing" },
]

# [char_sets.default] # previously 'extracompat'
# default_device = "*"
# default_stream = "*"
# selector_top = "-"
# selector_middle = "="
# selector_bottom = "-"
# tab_marker_left = "["
# tab_marker_right = "]"
# list_more = "~~~"
# volume_empty = "-"
# volume_filled = "="
# meter_left_inactive = "="
# meter_left_active = "#"
# meter_left_overload = "!"
# meter_right_inactive = "="
# meter_right_active = "#"
# meter_right_overload = "!"
# meter_center_left_inactive = "["
# meter_center_left_active = "["
# meter_center_right_inactive = "]"
# meter_center_right_active = "]"
# dropdown_icon = "\\"
# dropdown_selector = ">"
# dropdown_more = "~~~"
# dropdown_border = "Plain"
# help_more = "~~~"
# help_border = "Plain"
